blank_issues_enabled: false
contact_links:
  - name: Community support
    url: https://github.com/mockoon/mockoon/discussions
    about: Please ask and answer questions here.
  - name: Enterprise support
    url: https://mockoon.com/pricing/
    about: Get enterprise grade support
